package com.willclay.mapeditor.io;

import com.willclay.mapeditor.core.EditorModel;
import com.willclay.mapeditor.domain.Layer;
import com.willclay.mapeditor.domain.TileDef;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * Builds loader snippets that scan a layer's grid and populate a list of
 * objects, one switch case per distinct letter. Only layers holding at least
 * one Prop or Marker tile get a loader, and coordinates are passed as
 * (row, col) to match the Prop/Marker record component order. The class name
 * comes from the layer name, singularised:
 * "Props" gives Prop, "Markers" gives Marker.
 *
 * <pre>
 * List&lt;Prop&gt; propList = new ArrayList&lt;&gt;();
 * for (int row = 0; row &lt; props.length; row++)
 * {
 *     for (int col = 0; col &lt; props[row].length; col++)
 *     {
 *         switch (props[row][col])
 *         {
 *             case 't' -&gt; propList.add(new Prop("Torch", row, col));
 *         }
 *     }
 * }
 * </pre>
 */
public class LoaderExporter
{
    private static final String NOTHING_TO_LOAD =
            """
            // No Prop or Marker tiles found in any layer.
            // Mark tiles as category Prop or Marker in the palette to
            // generate loader snippets here.
            """;

    public static String exportLoaders(EditorModel model, String classPrefix)
    {
        StringBuilder sb = new StringBuilder();

        sb.append("// Generated by Tile Map Editor\n");
        sb.append("// Loader snippets: one list per layer containing props/markers\n\n");

        boolean any = false;
        for (int li = 0; li < model.getLayers().size(); li++)
        {
            Layer layer = model.getLayers().get(li);
            List<TileDef> entries = loadableTilesIn(model, layer, li);
            if (entries.isEmpty()) continue;

            appendLoader(sb, layer, entries, classPrefix);
            any = true;
        }

        return any ? sb.toString() : NOTHING_TO_LOAD;
    }

    /**
     * Distinct Prop/Marker tiles used by a layer, in first-seen (row-major)
     * order. Letters resolve per layer, since the same letter can map to a
     * different tile on each one.
     */
    private static List<TileDef> loadableTilesIn(EditorModel model, Layer layer, int layerIndex)
    {
        Set<Character> used = new LinkedHashSet<>();
        for (char[] row : layer.grid)
        {
            for (char letter : row)
            {
                if (letter != EditorModel.EMPTY) used.add(letter);
            }
        }

        List<TileDef> entries = new ArrayList<>();
        for (char letter : used)
        {
            TileDef tile = model.findTileForLayer(letter, layerIndex);
            if (tile != null && tile.isLoadable()) entries.add(tile);
        }

        return entries;
    }

    private static void appendLoader(StringBuilder sb, Layer layer, List<TileDef> entries, String classPrefix)
    {
        String className = JavaNames.classNameFor(layer.name);
        String listVar = JavaNames.lowerFirst(className) + "List";

        // The grid variable has to match what MapExporter declares.
        String gridVar = JavaNames.gridVariable(layer.name, classPrefix);

        sb.append("List<").append(className).append("> ").append(listVar).append(" = new ArrayList<>();\n");
        sb.append("for (int row = 0; row < ").append(gridVar).append(".length; row++)\n");
        sb.append("{\n");
        sb.append("    for (int col = 0; col < ").append(gridVar).append("[row].length; col++)\n");
        sb.append("    {\n");
        sb.append("        switch (").append(gridVar).append("[row][col])\n");
        sb.append("        {\n");

        for (TileDef tile : entries)
        {
            sb.append("            case ").append(caseLabel(tile, layer.isIntType()))
                    .append(" -> ").append(listVar)
                    .append(".add(new ").append(className).append("(\"")
                    .append(JavaNames.escapeString(tile.name)).append("\", row, col));\n");
        }

        sb.append("        }\n");
        sb.append("    }\n");
        sb.append("}\n\n");
    }

    private static String caseLabel(TileDef tile, boolean intLayer)
    {
        return intLayer ? String.valueOf(tile.id) : "'" + JavaNames.escapeChar(tile.letter) + "'";
    }
}