package com.willclay.mapeditor.io;

import com.willclay.mapeditor.core.EditorModel;
import com.willclay.mapeditor.domain.Layer;
import com.willclay.mapeditor.domain.TileDef;

/**
 * Writes each layer as a Java 2D array declaration, mirroring the formatting
 * style of the platformer's TileMap.java so exports drop straight in.
 */
public class MapExporter
{
    private static final String INDENT = "    ";

    public static String exportAsJava(EditorModel model, boolean quoteChars, String classPrefix)
    {
        StringBuilder sb = new StringBuilder();

        sb.append("// Generated by Tile Map Editor\n");
        sb.append("// Map Size: ").append(model.getCols()).append(" cols x ").append(model.getRows()).append(" rows")
                .append(", tile size: ").append(model.getTileSize()).append("px\n\n");

        for (int li = 0; li < model.getLayers().size(); li++)
        {
            Layer layer = model.getLayers().get(li);
            String varName = JavaNames.gridVariable(layer.name, classPrefix);

            if (layer.isIntType())
            {
                appendIntLayer(sb, model, layer, li, varName);
            }
            else
            {
                appendCharLayer(sb, model, layer, varName, quoteChars);
            }
        }

        return sb.toString();
    }

    private static void appendCharLayer(StringBuilder sb, EditorModel model, Layer layer,
            String varName, boolean quoteChars)
    {
        sb.append("char[][] ").append(varName).append(" = {\n");

        for (int r = 0; r < model.getRows(); r++)
        {
            sb.append(INDENT).append("{");

            for (int c = 0; c < model.getCols(); c++)
            {
                char letter = layer.grid[r][c];

                if (quoteChars)
                {
                    sb.append('\'').append(JavaNames.escapeChar(letter)).append('\'');
                    if (c < model.getCols() - 1) sb.append(",");
                }
                else
                {
                    sb.append(letter);
                }
            }

            appendRowEnd(sb, r, model.getRows());
        }

        sb.append("};\n\n");
    }

    private static void appendIntLayer(StringBuilder sb, EditorModel model, Layer layer,
            int layerIndex, String varName)
    {
        sb.append("int[][] ").append(varName).append(" = {\n");

        for (int r = 0; r < model.getRows(); r++)
        {
            sb.append(INDENT).append("{");

            for (int c = 0; c < model.getCols(); c++)
            {
                sb.append(idAt(model, layer, layerIndex, r, c));
                if (c < model.getCols() - 1) sb.append(",");
            }

            appendRowEnd(sb, r, model.getRows());
        }

        sb.append("};\n\n");
    }

    /** Resolve a cell to its tile id; empty cells and unknown letters are 0. */
    private static int idAt(EditorModel model, Layer layer, int layerIndex, int row, int col)
    {
        char letter = layer.grid[row][col];
        if (letter == EditorModel.EMPTY) return 0;

        TileDef tile = model.findTileForLayer(letter, layerIndex);

        return tile != null ? tile.id : 0;
    }

    private static void appendRowEnd(StringBuilder sb, int row, int rows)
    {
        sb.append("}");
        if (row < rows - 1) sb.append(",");
        sb.append("\n");
    }
}